### ISSUE TITLE
test.py RUN BUG 

### ISSUE THREAD

**Issue by 1316827294** [sustainable-computing/COBS#1]
windows10,python6.8

bug example:[
EnergyPlus Starting
EnergyPlus, Version 9.3.0-baff08990c, YMD=2021.06.30 00:45
Program terminated: EnergyPlus Terminated--Error(s) Detected.
**FATAL:Errors occurred on processing input file. Preceding condition(s) cause termination.
EnergyPlus Run Time=00hr 00min  0.19sec
]

**Comment by skyu0221** [comment]
Hi there,

All examples are under [./cobs/examples](https://github.com/sustainable-computing/COBS/tree/master/cobs/examples). The test.py file should not be committed and is removed now. Thanks!
